package MDLControlPanel;


/**
* MDLControlPanel/TimePanelInterfaceOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from ./src/MDLControlPanel.idl
* domenica 15 settembre 2013 16.59.01 CEST
*/

public interface TimePanelInterfaceOperations 
{
  int test (int num);
  void sendPilot (int num, String name, String car, String strategyStr, String fuel);
  void sendPilotIntermediate (int Number, String time, int numLap, int numIntermediate, int ticket, String totTime);
  void enterBox (int Number);
  void exitBox (int Number, String fuel);
  void sendRaceDescription (String name, String lenght, String numLap, String meteo);
  void sendStartRace ();
  void sendFuelAndTires (int number, String fuel, int tires);
  void sendFinishRace (int number, String time, int reason);
} // interface TimePanelInterfaceOperations
