package MDLControlPanel;


/**
* MDLControlPanel/TimePanelInterface.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from ./src/MDLControlPanel.idl
* lunedì 15 luglio 2013 15.05.17 CEST
*/

public interface TimePanelInterface extends TimePanelInterfaceOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface TimePanelInterface
