package MDLControlPanel;


/**
* MDLControlPanel/TimePanelInterface.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from ./src/MDLControlPanel.idl
* giovedì 19 settembre 2013 1.31.57 CEST
*/

public interface TimePanelInterface extends TimePanelInterfaceOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface TimePanelInterface
